version: '3'

services:
  eureka-server:
    build:
      context: ./eureka_server
      dockerfile: eureka_server.Dockerfile
    ports:
      - "8761:8761"

  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: api_gateway.Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server

  admin-user-service:
    build:
      context: ./admin_user_service
      dockerfile: admin_user_service.Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - api-gateway

  guest-user-service:
    build:
      context: ./guest_user_service
      dockerfile: guest_user_service.Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
      - api-gateway

  place-service:
    build:
      context: ./place_service
      dockerfile: place_service.Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    ports:
      - "8087:8087"
    depends_on:
      - eureka-server
      - api-gateway

  reservation-service:
    build:
      context: ./reservation_service
      dockerfile: reservation_service.Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server
      - api-gateway