global:
  scrape_interval: 15s
  evaluation_interval: 15s
  collect_disk_usage: false

scrape_configs:
  - job_name: 'eureka-server'
    static_configs:
      - targets: ['eureka-server:8761']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8081']

  - job_name: 'admin-user-service'
    static_configs:
      - targets: ['admin-user-service:8085']

  - job_name: 'guest-user-service'
    static_configs:
      - targets: ['guest-user-service:8086']

  - job_name: 'place-service'
    static_configs:
      - targets: ['place-service:8087']

  - job_name: 'reservation-service'
    static_configs:
      - targets: ['reservation-service:8088']

  - job_name: 'custom_jenkins'
    static_configs:
      - targets: ['custom_multi_jenkins:8080']

  - job_name: 'sonarqube'
    static_configs:
      - targets: ['sonarqube:9000']
    
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']