pipeline {
    environment {
        DOCKER_IMAGE = 'admin_user_service'
        DOCKER_REGISTRY = 'docker_hub_username'
        TAG = "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${env.BRANCH_NAME}"
    }

    //triggers {
    //    GenericTrigger(
    //        genericVariables: [
    //            [key: 'ref', value: '$.pull_request.head.ref'],
    //            [key: 'sha', value: '$.pull_request.head.sha']
    //        ],
    //        causeString: 'Triggered by GitHub pull request',
    //        domain: credentials('ngrok_domain')
    //        token: credentials('token'),
    //        printContributedVariables: true,
    //        printPostContent: true
    //    )
    //}

    stages {
        stage('Checkout') {
            steps {
                git branch: 'development',
                credentialsId: 'github_credential',
                url: 'https://github.com/SebestyenBenedek/table_reservation_backend.git'
            }
        }

        stage('Build') {
            steps {
                script {
                    checkout([$class: 'GitSCM', branches: [[name: "${ref}"]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/SebestyenBenedek/table_reservation_backend.git']]])
                }
                script {
                    sh 'cd admin_user_service'
                }
            }
        }

        
    }
}
